### ISSUE TITLE
Votación.js no se usa?

### ISSUE THREAD

**Issue by gmartineza** [Billones142/chacoEsculpe#8]
No encontré ninguna referencia a [votacion.js](https://github.com/Billones142/chacoEsculpe/blob/main/src/rutas/votacion.js).
Está obsoleto? Se puede eliminar el archivo?

**Comment by Billones142** [comment]
Eso es un codigo repetido de la parte de infraestructura, no se porque está ahí, me parece que stiven estaba viendo eso

**Comment by Lucas8276** [comment]
Este archivo ya no se usa. En la primera versión  si cumplía su función pero en esta es innecesario.
